name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, crystal: "1.20" }
          - { os: ubuntu-24.04-arm, crystal: "1.20" }
          - { os: macos-latest, crystal: "1.20" }
          - { os: macos-15-intel, crystal: "1.20" }
          - { os: windows-latest, crystal: "1.20" }

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}

      - name: Cache shards
        uses: actions/cache@v5
        with:
          path: |
            lib
            bin/ameba
          key: ${{ matrix.os }}-shards-${{ hashFiles('**/shard.lock') }}

      # ---- Build debug release and check code quality on all platforms

      - name: Install shards
        run: shards check || shards install

      - name: Run tests
        run: crystal spec -Dtest

      # ---- Build and run samples

      # - name: Setup release environment
      #   if: ${{ runner.os != 'Windows' }}
      #   run: mkdir -p bin/release

      # - name: Build Release
      #   if: ${{ runner.os != 'Windows' }}
      #   run: SHARDS_BIN_PATH=bin/release shards --production build --release

      # - name: Run test script runner
      #   if: ${{ runner.os != 'Windows' }}
      #   run: bin/release/test_runner

      # ---- format and lint check on Linux only

      - name: Check formatting (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: crystal tool format; git diff --exit-code src

      - name: Run static code analysis (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: bin/ameba src/
